package br.com.is.Entitys;
// Generated 13/09/2017 20:17:35 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "evento",
        schema = "public"
)
public class Evento implements java.io.Serializable {

    private int codigo;
    private Endereco endereco;
    private TipoEvento tipoEvento;
    private Date horainicio;
    private Date horatermino;
    private String descricao;
    private Boolean ativo;
    private ServicoPertenceEvento servicoPertenceEvento;

    public Evento() {
    }

    public Evento(int codigo, Endereco endereco, TipoEvento tipoEvento) {
        this.codigo = codigo;
        this.endereco = endereco;
        this.tipoEvento = tipoEvento;
    }

    public Evento(int codigo, Endereco endereco, TipoEvento tipoEvento, Date horainicio, Date horatermino, String descricao, Boolean ativo, ServicoPertenceEvento servicoPertenceEvento) {
        this.codigo = codigo;
        this.endereco = endereco;
        this.tipoEvento = tipoEvento;
        this.horainicio = horainicio;
        this.horatermino = horatermino;
        this.descricao = descricao;
        this.ativo = ativo;
        this.servicoPertenceEvento = servicoPertenceEvento;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "codigo", unique = true, nullable = false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "endereco", nullable = false)
    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_evento", nullable = false)
    public TipoEvento getTipoEvento() {
        return this.tipoEvento;
    }

    public void setTipoEvento(TipoEvento tipoEvento) {
        this.tipoEvento = tipoEvento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "horainicio", length = 13)
    public Date getHorainicio() {
        return this.horainicio;
    }

    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "horatermino", length = 13)
    public Date getHoratermino() {
        return this.horatermino;
    }

    public void setHoratermino(Date horatermino) {
        this.horatermino = horatermino;
    }

    @Column(name = "descricao", length = 150)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "ativo")
    public Boolean getAtivo() {
        return this.ativo;
    }

    public void setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "evento")
    public ServicoPertenceEvento getServicoPertenceEvento() {
        return this.servicoPertenceEvento;
    }

    public void setServicoPertenceEvento(ServicoPertenceEvento servicoPertenceEvento) {
        this.servicoPertenceEvento = servicoPertenceEvento;
    }

}
