package br.com.is.Entitys;
// Generated 13/09/2017 20:17:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PacotePossuiServicoId generated by hbm2java
 */
@Embeddable
public class PacotePossuiServicoId  implements java.io.Serializable {


     private int pacote;
     private int servico;

    public PacotePossuiServicoId() {
    }

    public PacotePossuiServicoId(int pacote, int servico) {
       this.pacote = pacote;
       this.servico = servico;
    }
   


    @Column(name="pacote", nullable=false)
    public int getPacote() {
        return this.pacote;
    }
    
    public void setPacote(int pacote) {
        this.pacote = pacote;
    }


    @Column(name="servico", nullable=false)
    public int getServico() {
        return this.servico;
    }
    
    public void setServico(int servico) {
        this.servico = servico;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PacotePossuiServicoId) ) return false;
		 PacotePossuiServicoId castOther = ( PacotePossuiServicoId ) other; 
         
		 return (this.getPacote()==castOther.getPacote())
 && (this.getServico()==castOther.getServico());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPacote();
         result = 37 * result + this.getServico();
         return result;
   }   


}


