package br.com.is.Entitys;
// Generated 13/09/2017 20:17:35 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PacotePossuiServico generated by hbm2java
 */
@Entity
@Table(name = "pacote_possui_servico",
         schema = "public"
)
public class PacotePossuiServico implements java.io.Serializable {

    private PacotePossuiServicoId id;
    private Equipe equipe;
    private Servico servico;
    private BigDecimal valorServico;
    private Date propostaEm;

    public PacotePossuiServico() {
    }

    public PacotePossuiServico(PacotePossuiServicoId id, Equipe equipe, Servico servico) {
        this.id = id;
        this.equipe = equipe;
        this.servico = servico;
    }

    public PacotePossuiServico(PacotePossuiServicoId id, Equipe equipe, Servico servico, BigDecimal valorServico, Date propostaEm) {
        this.id = id;
        this.equipe = equipe;
        this.servico = servico;
        this.valorServico = valorServico;
        this.propostaEm = propostaEm;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "pacote", column = @Column(name = "pacote", nullable = false))
        , 
        @AttributeOverride(name = "servico", column = @Column(name = "servico", nullable = false))})
    public PacotePossuiServicoId getId() {
        return this.id;
    }

    public void setId(PacotePossuiServicoId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pacote", nullable = false, insertable = false, updatable = false)
    public Equipe getEquipe() {
        return this.equipe;
    }

    public void setEquipe(Equipe equipe) {
        this.equipe = equipe;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "servico", nullable = false, insertable = false, updatable = false)
    public Servico getServico() {
        return this.servico;
    }

    public void setServico(Servico servico) {
        this.servico = servico;
    }

    @Column(name = "valor_servico", precision = 5)
    public BigDecimal getValorServico() {
        return this.valorServico;
    }

    public void setValorServico(BigDecimal valorServico) {
        this.valorServico = valorServico;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "proposta_em", length = 13)
    public Date getPropostaEm() {
        return this.propostaEm;
    }

    public void setPropostaEm(Date propostaEm) {
        this.propostaEm = propostaEm;
    }

}
