package br.com.is.Entitys;
// Generated 13/09/2017 20:17:35 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servico generated by hbm2java
 */
@Entity
@Table(name = "servico",
        schema = "public"
)
public class Servico implements java.io.Serializable {

    private int codigo;
    private Equipe equipe;
    private String titulo;
    private String descricao;
    private BigDecimal valor;
    private Set<PacotePossuiServico> pacotePossuiServicos = new HashSet<PacotePossuiServico>(0);
    private Set<ServicoPertenceEvento> servicoPertenceEventos = new HashSet<ServicoPertenceEvento>(0);

    public Servico() {
    }

    public Servico(int codigo) {
        this.codigo = codigo;
    }

    public Servico(int codigo, Equipe equipe, String titulo, String descricao, BigDecimal valor, Set<PacotePossuiServico> pacotePossuiServicos, Set<ServicoPertenceEvento> servicoPertenceEventos) {
        this.codigo = codigo;
        this.equipe = equipe;
        this.titulo = titulo;
        this.descricao = descricao;
        this.valor = valor;
        this.pacotePossuiServicos = pacotePossuiServicos;
        this.servicoPertenceEventos = servicoPertenceEventos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "codigo", unique = true, nullable = false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "equipe")
    public Equipe getEquipe() {
        return this.equipe;
    }

    public void setEquipe(Equipe equipe) {
        this.equipe = equipe;
    }

    @Column(name = "titulo", length = 75)
    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    @Column(name = "descricao")
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "valor", precision = 5)
    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "servico")
    public Set<PacotePossuiServico> getPacotePossuiServicos() {
        return this.pacotePossuiServicos;
    }

    public void setPacotePossuiServicos(Set<PacotePossuiServico> pacotePossuiServicos) {
        this.pacotePossuiServicos = pacotePossuiServicos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "servico")
    public Set<ServicoPertenceEvento> getServicoPertenceEventos() {
        return this.servicoPertenceEventos;
    }

    public void setServicoPertenceEventos(Set<ServicoPertenceEvento> servicoPertenceEventos) {
        this.servicoPertenceEventos = servicoPertenceEventos;
    }

}
