package br.com.is.Entitys;
// Generated 13/09/2017 20:17:35 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ServicoPertenceEvento generated by hbm2java
 */
@Entity
@Table(name = "servico_pertence_evento",
        schema = "public"
)
public class ServicoPertenceEvento implements java.io.Serializable {

    private int eventoCod;
    private Evento evento;
    private Servico servico;
    private BigDecimal valorOriginal;
    private BigDecimal valorFinal;

    public ServicoPertenceEvento() {
    }

    public ServicoPertenceEvento(Evento evento, Servico servico, BigDecimal valorOriginal, BigDecimal valorFinal) {
        this.evento = evento;
        this.servico = servico;
        this.valorOriginal = valorOriginal;
        this.valorFinal = valorFinal;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "evento"))
    @Id
    @GeneratedValue(generator = "generator")

    @Column(name = "evento_cod", unique = true, nullable = false)
    public int getEventoCod() {
        return this.eventoCod;
    }

    public void setEventoCod(int eventoCod) {
        this.eventoCod = eventoCod;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Evento getEvento() {
        return this.evento;
    }

    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "servico", nullable = false)
    public Servico getServico() {
        return this.servico;
    }

    public void setServico(Servico servico) {
        this.servico = servico;
    }

    @Column(name = "valor_original", nullable = false, precision = 5)
    public BigDecimal getValorOriginal() {
        return this.valorOriginal;
    }

    public void setValorOriginal(BigDecimal valorOriginal) {
        this.valorOriginal = valorOriginal;
    }

    @Column(name = "valor_final", nullable = false, precision = 5)
    public BigDecimal getValorFinal() {
        return this.valorFinal;
    }

    public void setValorFinal(BigDecimal valorFinal) {
        this.valorFinal = valorFinal;
    }

}
