package br.com.is.Entitys;
// Generated 13/09/2017 20:17:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContato generated by hbm2java
 */
@Entity
@Table(name = "tipo_contato",
        schema = "public"
)
public class TipoContato implements java.io.Serializable {

    private int codigo;
    private String nome;
    private String sigla;
    private String descricao;
    private Set<PossuiContato> possuiContatos = new HashSet<PossuiContato>(0);

    public TipoContato() {
    }

    public TipoContato(int codigo) {
        this.codigo = codigo;
    }

    public TipoContato(int codigo, String nome, String sigla, String descricao, Set<PossuiContato> possuiContatos) {
        this.codigo = codigo;
        this.nome = nome;
        this.sigla = sigla;
        this.descricao = descricao;
        this.possuiContatos = possuiContatos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "codigo", unique = true, nullable = false)
    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    @Column(name = "nome", length = 75)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "sigla", length = 3)
    public String getSigla() {
        return this.sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    @Column(name = "descricao", length = 150)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContato")
    public Set<PossuiContato> getPossuiContatos() {
        return this.possuiContatos;
    }

    public void setPossuiContatos(Set<PossuiContato> possuiContatos) {
        this.possuiContatos = possuiContatos;
    }

}
